Vagrant.configure("2") do |config|
  config.vm.define "upf" do |vm|
    vm.vm.box = "ubuntu/focal64"
    vm.vm.hostname = "upf"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet1"]
      # vb.customize ["modifyvm", :id, "--nic3", "hostonly", "--hostonlyadapter3", "vboxnet2"]
    end

    vm.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbook.yml"
      ansible.extra_vars = {
        ovs: true,
        python: true,
        aioquic: true,
        dnslib: false,
      }
    end
  end

  config.vm.define "easdf" do |vm|
    vm.vm.box = "ubuntu/focal64"
    vm.vm.hostname = "easdf"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet1"]
      vb.customize ["modifyvm", :id, "--nic3", "hostonly", "--hostonlyadapter3", "vboxnet2"]
    end

    vm.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbook.yml"
      ansible.extra_vars = {
        ovs: true,
        python: true,
        aioquic: false,
        dnslib: true,
      }
    end
  end

  config.vm.define "asdf" do |vm|
    vm.vm.box = "ubuntu/focal64"
    vm.vm.hostname = "asdf"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet1"]
      vb.customize ["modifyvm", :id, "--nic3", "hostonly", "--hostonlyadapter3", "vboxnet2"]
    end

    vm.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbook.yml"
      ansible.extra_vars = {
        ovs: true,
        python: true, 
        aioquic: true,
        dnslib: false,
      }
    end
  end

  config.vm.define "server" do |vm|
    vm.vm.box = "ubuntu/focal64"
    vm.vm.hostname = "server"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet1"]
      vb.customize ["modifyvm", :id, "--nic3", "hostonly", "--hostonlyadapter3", "vboxnet2"]
    end

    vm.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbook.yml"
      ansible.extra_vars = {
        ovs: false,
        python: true, 
        aioquic: true,
        dnslib: false,
      }
    end
  end

  config.vm.define "pubsub" do |vm|
    vm.vm.box = "ubuntu/focal64"
    vm.vm.hostname = "pubsub"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--nic3", "hostonly", "--hostonlyadapter3", "vboxnet2"]
    end

    vm.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/playbook.yml"
      ansible.extra_vars = {
        ovs: false,
        python: false,
        aioquic: false,
        dnslib: false,
      }
    end
  end
end
