- hosts: upf
  become: yes
  tasks:
    - name: Reset the routing table of UPF
      shell: |
        ip route del default
        ip route add default via 10.0.2.2 
- hosts: all
  become: yes
  tasks:
    - name: Install essential packets
      apt:
        update_cache: true
        name:
          - net-tools
          - vim
          - tmux
          - libssl-dev
        state: present
    - name: Install Open vSwitch
      when: ovs == true
      apt:
        name: 
          - openvswitch-switch
          - openvswitch-common
        state: present
    - name: Install Python
      when: python == true
      apt:
        name:
          - python3.8
          - python3-pip
          - ipython3
        state: present
    - name: Install dns_ttl.py python package
      when: dnslib == true
      pip:
        name: dnslib
    # - name: Copy aioquic
    #   when: aioquic == true
    #   synchronize:
    #     src: ../../submodules/aioquic
    #     dest: ~/libs 
    #   register: aioquic_copy
    # - name: Install aioquic
    #   when: aioquic == true and aioquic_copy|success
    #   shell: 
    #     chdir: ~/libs/aioquic
    #     cmd: python setup install
    # - name: Copy project files
    #   copy:
    #     src: ../../src
    #     dest: ~/python 
    # - name: Copy scripts
    #   copy:
    #     src: ../../scripts/run.sh
    #     dest: ~/run.sh
    #     register: copy_script
    # - name: Run programs
    #   when: copy_script|success
    #   shell: ~/run.sh
- hosts: upf
  become: yes
  tasks:
    - name: Init network
      shell: |
          ifconfig enp0s8 192.168.57.11 up
          ovs-vsctl del-br br0
          ovs-vsctl add-br br0
          ovs-vsctl set bridge br0 other_config:hwaddr=3a:4d:a7:05:2a:11
          ovs-vsctl add-port br0 gre0 -- set interface gre0 type=gre options:remote_ip=192.168.57.12
          ifconfig br0 10.0.10.11
          arp -s 10.0.10.12 3a:4d:a7:05:2a:12 
          ovs-ofctl del-flows br0
          ovs-ofctl add-flow br0 in_port=gre0,actions=br0
          ovs-ofctl add-flow br0 in_port=br0,actions=gre0
          echo 192.168.58.13 aeacus.xuebing.me >> /etc/hosts
- hosts: asdf
  become: yes
  tasks:
    - name: Init network
      shell: |
          ifconfig enp0s8 192.168.57.12 up
          ifconfig enp0s9 192.168.58.12 up
          ovs-vsctl del-br br0
          ovs-vsctl add-br br0
          ovs-vsctl set bridge br0 other_config:hwaddr=3a:4d:a7:05:2a:12
          ovs-vsctl add-port br0 gre0 -- set interface gre0 type=gre options:remote_ip=192.168.57.11
          ovs-vsctl add-port br0 gre1 -- set interface gre1 type=gre options:remote_ip=192.168.57.13
          ovs-ofctl del-flows br0
          ovs-ofctl add-flow br0 in_port=gre0,ip,nw_proto=17,nw_dst=192.168.58.13/32,actions=gre1,mod_nw_dst:10.0.10.13
          ovs-ofctl add-flow br0 in_port=gre0,actions=br0
          ovs-ofctl add-flow br0 in_port=br0,actions=gre0
          ovs-ofctl add-flow br0 in_port=gre1,actions=br0
          ifconfig br0 10.0.10.12
          arp -s 10.0.10.11 3a:4d:a7:05:2a:11 
          arp -s 10.0.10.13 3a:4d:a7:05:2a:13 
          modprobe iptable_nat
          sysctl -w net.ipv4.ip_forward=1
          iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
          iptables -A FORWARD -i br0 -j ACCEPT
- hosts: easdf
  become: yes
  tasks:
    - name: Init network
      shell: |
          ifconfig enp0s8 192.168.57.13 up
          ifconfig enp0s9 192.168.58.13 up
          ovs-vsctl del-br br0
          ovs-vsctl add-br br0
          ovs-vsctl set bridge br0 other_config:hwaddr=3a:4d:a7:05:2a:13
          ovs-vsctl add-port br0 gre1 -- set interface gre1 type=gre options:remote_ip=192.168.57.12
          ifconfig br0 10.0.10.13
          arp -s 10.0.10.11 3a:4d:a7:05:2a:11
          arp -s 10.0.10.12 3a:4d:a7:05:2a:12
          ovs-ofctl del-flows br0
          ovs-ofctl add-flow br0 in_port=gre1,actions=br0,mod_nw_dst:10.0.10.13
          ovs-ofctl add-flow br0 in_port=br0,actions=gre1,mod_dl_src:3a:4d:a7:05:2a:13
    - name: Init python 3.11
      shell: |
          add-apt-repository -y ppa:deadsnakes/ppa
          apt update
          apt install -y python3.11-dev python3.11-distutils
          wget https://bootstrap.pypa.io/get-pip.py
          python3.11 get-pip.py
          python3.11 -m pip install dnslib
- hosts: pubsub
  become: yes
  tasks:
    - name: Init network
      shell: |
          ifconfig enp0s9 192.168.58.14 up
    - name: Install software
      apt:
        name:
          - mosquitto
        state: present
- hosts: server1
  become: yes
  tasks:
    - name: Init network
      shell: |
          ifconfig enp0s9 192.168.58.15 up
    - name: Install python libs
      pip:
        name: paho-mqtt
- hosts: server2
  become: yes
  tasks:
    - name: Init network
      shell: |
          ifconfig enp0s9 192.168.58.16 up
    - name: Install python libs
      pip:
        name: paho-mqtt
